[package]
name = "rcode"
version = "0.1.0"
edition = "2024"

[dependencies]
async-openai = { version = "0.35.0", features = ["full"] }
crossterm = "0.29.0"
futures = "0.3.32"
ratatui = { version = "0.30.0", features = ["unstable-rendered-line-info"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
tempfile = "3.27.0"
termimad = "0.34.1"
tokio = { version = "1", features = ["full"] }
toml = "1.1.2"
unicode-width = "0.2.2"
